# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "09b414e0b4717bf7de0c61d5e7a90984"
name = "Shoprift"
application_url = "https://shoprift.app"
embedded = true

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://shoprift.app/api/webhooks/compliance"

[[webhooks.subscriptions]]
topics = ["app_purchases_one_time/update"]
uri = "https://shoprift.app/api/webhooks/billing-update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_product_listings,write_products"

[auth]
redirect_urls = [
  "https://shoprift.app/api/auth/callback"
]

[pos]
embedded = false
